// 1. DEFINIR O MODELO DE LIVROS COM SEUS RESPECTIVOS CAMPOS E TIPOS DE DADOS (id, category_id, title, author, description, publishedDate, available)
// 2. CRIAR O MODELO NO MODELS
// 3. IMPORTAR NO MODEL/INDEX.JS, RODAR O PROJETO PARA CRIAR A TABELA NO BANCO DE DADOS
// 4. CRIAR O CONTROLLER PARA MANIPULAR OS DADOS DO MODELO
// 5. CRIAR AS ROTAS PARA INTERAGIR COM O CONTROLLER
// 6. IMPORTAR AS ROTAS NO ARQUIVO PRINCIPAL E TESTAR AS ROTAS COM POSTMAN